apiVersion: v1
kind: Service
spec:
  ports:
    - port: #{Project.Web.Http.Port}
      targetPort: #{Project.Web.Http.Port}
    - port: #{Project.Web.Https.Port}
      targetPort: #{Project.Web.Https.Port}