apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: web
          ports:
            - containerPort: #{Project.Web.Http.Port}
            - containerPort: #{Project.Web.Https.Port}