apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: productservice
          env:
            - name: OPSConnectionString
              value: Data Source=octopetshop-sqlserver-cluster-ip-service;Initial Catalog=OctoPetShop; User ID=sa; Password=#{Project.SQLServer.SA.Password}