version: '3.5'

services:
  sql-server:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "OctopusDeploy_1234"
      ACCEPT_EULA: "Y"
  octopussamples.octopetshop.productservice:
    environment:
      - OPSConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    image: ${DOCKER_REGISTRY-}octopussamplesoctopetshopproductservice
    build:
      context: .
      dockerfile: OctopusSamples.OctoPetShop.ProductService/Dockerfile
    ports:
      - '5011:80'
      - '5014:443'
    depends_on: 
      - "octopussamples.octopetshop.database"

  octopussamples.octopetshop.shoppingcartservice:
    image: ${DOCKER_REGISTRY-}octopussamplesoctopetshopshoppingcartservice
    build:
      context: .
      dockerfile: OctopusSamples.OctoPetShop.ShoppingCartService/Dockerfile
    environment:
      - OPSConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    ports:
      - '5012:80'
      - '5013:443'
    depends_on: 
      - "octopussamples.octopetshop.database"

  octopussamples.octopetshop.web:
    image: ${DOCKER_REGISTRY-}octopussamplesoctopetshopweb
    build:
      context: .
      dockerfile: OctopusSamples.OctoPetShop.Web/Dockerfile
    environment:
      - ProductServiceBaseUrl=http://octopussamples.octopetshop.productservice:5011/
      - ShoppingCartServiceBaseUrl=http://octopussamples.octopetshop.shoppingcartservice:5012
    ports:
      - '5000:80'
      - '5001:443'
    depends_on: 
      - "octopussamples.octopetshop.shoppingcartservice"
      - "octopussamples.octopetshop.productservice"

  octopussamples.octopetshop.database:
    environment:
      - DbUpConnectionString=Data Source=sql-server;Initial Catalog=OctoPetShop; User ID=sa; Password=OctopusDeploy_1234
    image: ${DOCKER_REGISTRY-}octopussamplesoctopetshopdatabase
    build:
      context: .
      dockerfile: OctopusSamples.OctoPetShop.Database/Dockerfile
    depends_on: 
      - "sql-server" 
