apiVersion: v1
kind: Service
metadata:
  name: octopetshop-productservice-cluster-ip-service
spec:
  type: CluserIP
  selector:
    component: productservice
  ports:
    - port: 5011
      targetPort: 5011
    - port: 5014
      targetPort: 5014