apiVersion: v1
kind: Service
metadata:
  name: octopetshop-shoppingcart-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: shoppingcartservice
  ports:
    - port: 5012
      targetPort: 80
      name: http-port
    - port: 5013
      targetPort: 443
      name: https-port