apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  template:
    spec:
      containers:
        - name: sqlserver
          env:
            - name: SA_PASSWORD
              value: "#{Project.SQLServer.SA.Password}"
            - name: ACCEPT_EULA
              value: "Y"