apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    component: web
  ports:
    - port: #{Project.Web.Http.Port}
      name: http-port
      targetPort: #{Project.Web.Http.Port}
    - port: #{Project.Web.Https.Port}
      name: https-port
      targetPort: #{Project.Web.Https.Port}
  